### ISSUE TITLE
验证动态添加数据库有点问题，麻烦请教下了，在插入数据的时候，走sharding这块拿到值是空

### ISSUE THREAD

**Issue by zhulei111** [henyi-c/shardingjdbc-date-algorithm#2]
![image](https://user-images.githubusercontent.com/7446487/153177598-12b4d0fc-6d5c-4065-bb2e-7db4749236bd.png)

**Comment by henyi-c** [comment]
更新了一下sharding配置，那个开关没有打开，更新了对应的postman，可以去测试一下
