### ISSUE TITLE
关于自动建表类的问题

### ISSUE THREAD

**Issue by hhyazj** [henyi-c/shardingjdbc-date-algorithm#3]
按时间分表时，自动建表类，会去扫描数据库中表，初始表名：tb_allianceorder，由于我数据库中另一张表tb_allianceorder_old，引发了错误。也就是说前缀一样的表，是会起冲突的，这个问题有没有优化的办法呢，求助各位大佬。
![image](https://user-images.githubusercontent.com/27292283/221078797-012683ad-bfda-4035-9845-a1d8a37f46fc.png)

**Comment by hhyazj** [comment]
![image](https://user-images.githubusercontent.com/27292283/221085071-e7c8bb46-5fa0-4435-abea-d274a46c2691.png)

**Comment by henyi-c** [comment]
已更新处理前缀问题，tb_allianceorder_后缀为非数字相关会进行过滤，数字仍存在该问题（关乎业务暂不进行修改）

**Comment by hhyazj** [comment]
up，我是这样改的，有点简单粗暴的方式，这样改也能避免这个前缀的问题。
![1677464893627](https://user-images.githubusercontent.com/27292283/221458527-f9550961-6450-4fb1-9143-67f9d3540ae6.jpg)
